export const portfolioData = [
  {
    id: "1",
    name: "SPEC ONE",
    tradeDesk: "TREASURY",
    cashiers: "NA",
    subCashiers: "NA",
    alias: "Outbook",
    dataflow: "SPEC ONE",
    realPC: "SPEC ONE",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC ONE (001)",
    status: "confirmed",
  },
  {
    id: "2",
    name: "SPEC TWO",
    tradeDesk: "AY FIXED INCOME TRAD",
    cashiers: "AY FIXED edited",
    subCashiers: "13 X 16 edited",
    alias: "Outbook",
    dataflow: "SPEC TWO",
    realPC: "SPEC TWO",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC TWO (001), SPEC TWO (001), SPEC TWO (001), SPEC TWO (001), SPEC TWO (001)",
    status: "confirmed",
  },
  {
    id: "3",
    name: "SPEC THREE",
    tradeDesk: "AY FIXED INCOME TRAD",
    cashiers: "AY FIXED edited",
    subCashiers: "17 X 16",
    alias: "Outbook",
    dataflow: "SPEC THREE",
    realPC: "SPEC THREE",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC THREE (001), SPEC THREE (001), SPEC THREE (001), SPEC THREE (001)",
    status: "confirmed",
  },
  {
    id: "4",
    name: "17 X 16",
    tradeDesk: "AY FIXED INCOME TRAD",
    cashiers: "AY FIXED edited",
    subCashiers: "17 X 16",
    alias: "Outbook",
    dataflow: "17 X 16",
    realPC: "17 X 16",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC THREE (001), SPEC THREE (001), SPEC THREE (001), SPEC THREE (001)",
    status: "confirmed",
  },
  {
    id: "5",
    name: "17 X 16.01",
    tradeDesk: "AY FIXED INCOME TRAD",
    cashiers: "AY FIXED edited",
    subCashiers: "24 X 16",
    alias: "Outbook",
    dataflow: "17 X 16.01",
    realPC: "17 X 16.01",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC THREE (001), SPEC THREE (001), SPEC THREE (001), SPEC THREE (001)",
    status: "confirmed",
  },
  {
    id: "6",
    name: "24 X 16",
    tradeDesk: "AY FIXED INCOME TRAD",
    cashiers: "AY FIXED edited",
    subCashiers: "27 X 16",
    alias: "Outbook",
    dataflow: "24 X 16",
    realPC: "24 X 16",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC THREE (001), SPEC THREE (001), SPEC THREE (001), SPEC THREE (001)",
    status: "confirmed",
  },
  {
    id: "7",
    name: "27 X 16",
    tradeDesk: "AY FIXED INCOME TRAD",
    cashiers: "AY FIXED edited",
    subCashiers: "27 X 16",
    alias: "Outbook",
    dataflow: "27 X 16",
    realPC: "27 X 16",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC THREE (001), SPEC THREE (001), SPEC THREE (001), SPEC THREE (001)",
    status: "confirmed",
  },
  {
    id: "8",
    name: "SPEC ARBITRAGE",
    tradeDesk: "BROKERAGE",
    cashiers: "ARBITRAGE",
    subCashiers: "SPEC11",
    alias: "Outbook",
    dataflow: "SPEC ARBITRAGE",
    realPC: "SPEC ARBITRAGE",
    bookStore: "test1 (001), -test1 (001), test1 (001), test1 (001), test1 (CT)",
    bookBS: "SPEC THREE (001), SPEC THREE (001), SPEC THREE (001), SPEC THREE (001)",
    status: "confirmed",
  },
];

export const tradeDeskData = [
  {
    id: "1",
    name: "SPEC ONE",
    description: "Click here to add a new row",
    account: "TREASURY",
    alias: "NA",
    code: "1",
    description2: "Click here to add a new row",
    date: "NA",
    description3: "Click here to add a new row",
    status: "confirmed",
  },
  {
    id: "2",
    name: "SPEC (EUR/ZL)",
    description: "SPEC (EUR/ZL)",
    account: "SPEC (EUR/ZL)",
    alias: "DA",
    code: "2",
    description2: "SPEC (EUR/ZL)",
    date: "DA",
    description3: "SPEC (EUR/ZL)",
    status: "confirmed",
  },
  {
    id: "3",
    name: "ABS OPTIONS",
    description: "ABS OPTIONS",
    account: "ABS OPTIONS - BRAZIL",
    alias: "DA",
    code: "3",
    description2: "ABS OPTIONS",
    date: "DA",
    description3: "ABS OPTIONS",
    status: "confirmed",
  },
  {
    id: "4",
    name: "ABS OPTIONS - BRAZIL",
    description: "ABS OPTIONS - BRAZIL",
    account: "ABS OPTIONS - BRAZIL",
    alias: "DA",
    code: "4",
    description2: "ABS OPTIONS - BRAZIL",
    date: "DA",
    description3: "ABS OPTIONS - BRAZIL",
    status: "confirmed",
  },
];

export const cashiersData = [
  {
    id: "1",
    name: "SPEC (EUR/ZL)",
    description: "Click here to add a new row",
    account: "SPEC (EUR/ZL)",
    alias: "DA",
    code: "1",
    description2: "Click here to add a new row",
    date: "2021 - test1",
    description3: "Click here to add a new row",
    status: "confirmed",
  },
  {
    id: "2",
    name: "ABS OPTIONS",
    description: "ABS OPTIONS",
    account: "ABS OPTIONS - BRAZIL",
    alias: "DA X 13",
    code: "2",
    description2: "ABS OPTIONS",
    date: "2021 - test1.01",
    description3: "ABS OPTIONS",
    status: "confirmed",
  },
  {
    id: "3",
    name: "ABS OPTIONS - BRAZIL",
    description: "ABS OPTIONS - BRAZIL",
    account: "ABS OPTIONS - BRAZIL",
    alias: "DA X 13",
    code: "3",
    description2: "ABS OPTIONS - BRAZIL",
    date: "DA X 13",
    description3: "ABS OPTIONS - BRAZIL",
    status: "confirmed",
  },
];

export const subCashiersData = [
  {
    id: "1",
    name: "SPEC (EUR/ZL)",
    description: "Click here to add a new row",
    account: "SPEC (EUR/ZL)",
    alias: "DA",
    code: "1",
    description2: "Click here to add a new row",
    date: "2021 - test1",
    description3: "Click here to add a new row",
    status: "confirmed",
  },
  {
    id: "2",
    name: "ABS OPTIONS",
    description: "ABS OPTIONS",
    account: "ABS OPTIONS - BRAZIL",
    alias: "DA X 13",
    code: "2",
    description2: "ABS OPTIONS",
    date: "2021 - test1.01",
    description3: "ABS OPTIONS",
    status: "confirmed",
  },
];

export const bookStoreData = [
  {
    id: "1",
    name: "SPEC (EUR/ZL)",
    description: "Click here to add a new row",
    account: "SPEC (EUR/ZL)",
    alias: "DA",
    code: "1",
    description2: "Click here to add a new row",
    date: "2021 - test1",
    description3: "Click here to add a new row",
    status: "confirmed",
  },
  {
    id: "2",
    name: "ABS OPTIONS",
    description: "ABS OPTIONS",
    account: "ABS OPTIONS - BRAZIL",
    alias: "DA X 13",
    code: "2",
    description2: "ABS OPTIONS",
    date: "2021 - test1.01",
    description3: "ABS OPTIONS",
    status: "confirmed",
  },
];
